version: '3'

services:
  gateway:
    image: gateway
    build: 
      context: ./gateway-service/.
      dockerfile: ./Dockerfile
    ports:
      - '9090:9090'
    container_name: gateway-container
    restart: unless-stopped

  user-service:
    image: user-service
    build:
      context: ./user-service/.
      dockerfile: ./Dockerfile
    environment:
      - MONGO_USERNAME=${MONGO_USER_SERVICE_USERNAME}
      - MONGO_PASSWORD=${MONGO_USER_SERVICE_PASSWORD}
      - MONGO_DB_NAME=${INIT_DATABASE}
    ports:
      - '8008:8008'
    container_name: user-container
    restart: unless-stopped

  user-mongo:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${INIT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${INIT_PASSWORD}
      - MONGO_INITDB_DATABASE=${INIT_DATABASE}
      - MONGO_USER_SERVICE_USERNAME=${MONGO_USER_SERVICE_USERNAME}
      - MONGO_USER_SERVICE_PASSWORD=${MONGO_USER_SERVICE_PASSWORD}
    ports: 
      - "27017:27017"
    volumes:
      - ./scripts/user-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  
  