version: '3'

services:

  music-service:
    image: music-service
    environment:
       - MONGO_USERNAME=${MONGO_MUSIC_SERVICE_USERNAME}
       - MONGO_PASSWORD=${MONGO_MUSIC_SERVICE_PASSWORD}
       - MONGO_DB_NAME=${MONGO_INITDB_DATABASE}
       - AWS_BUCKET_REGION=${AWS_BUCKET_REGION}
       - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
       - AWS_ACCESS_KEY=${AWS_ACCESS_KEY}
       - AWS_SECRET_KEY=${AWS_SECRET_KEY}
    build:
      context: ./music-service/.
      dockerfile: ./Dockerfile
    ports:
      - '8888:8888'
    depends_on:
      - mongo
    container_name: music-container
    restart: unless-stopped

  mongo:
    image: mongo:latest
    env_file:
      - .env
    ports: 
      - "27017:27017"
    volumes:
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro